# environment:
#   chocolateyApiKey:
#     secure: CPNSQvKUxo8opfNw9helbxnbt62zLmFDFt9fAbCUBuT9VWsQlzDw4f0t9rmbRCe9

build: off

# deploy:
#   - provider: Environment
#     name: production
#     on:
#       APPVEYOR_REPO_TAG: true


test_script:
  - ps: |
      # Create Chocolately Package
      Choco Pack .\emacs.nuspec
      # Try to install the package
      Choco Install emacs -source .\ -forcex86 -y
      Choco Uninstall emacs -y
      Choco Install emacs -source .\ -y

      # Create Emacs full Chocolately Package
      Choco Pack .\emacs-full.nuspec
      # Try to install the package
      Choco Install emacs-full -source .\ -forcex86 -y
      Choco Uninstall emacs-full -y
      Choco Install emacs-full -source .\ -y

# deploy_script:
#   - ps: |
#       # Create Chocolately Package
#       Choco Pack
#       # save the artifact
#       $version = ([xml](Get-Content .\emacs.nuspec)).package.metadata.version
#       Push-AppveyorArtifact ".\Emacs.$version.nupkg"
#       Choco apikey --key $chocolateyApiKey --source https://push.chocolatey.org/
#       Choco push ".\Emacs.$version.nupkg" --source https://push.chocolatey.org/
