build: off

test_script:
  - ps: |
      # Create Chocolately Package
      Choco Pack
      # Try to install the package
      Choco Install Emacs -source .\ -forcex86
      Choco Uninstall Emacs
      Choco Install Emacs -source .\

deploy_script:
  - ps: |
      # Create Chocolately Package
      Choco Pack
      # save the artifact
      $version = ([xml](Get-Content .\emacs.nuspec)).package.metadata.version      
      Push-AppveyorArtifact ".\Emacs.$version.nupkg"
