# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-2019

steps:
- powershell: |
      # Create Chocolately Package
      Choco Pack .\emacs.nuspec
      # Try to install the package
      Choco Install emacs -source .\ -forcex86 -y
      Choco Uninstall emacs -y
      Choco Install emacs -source .\ -y

      # Create Emacs full Chocolately Package
      Choco Pack .\emacs-full.nuspec
      # Try to install the package
      Choco Install emacs-full -source .\ -forcex86 -y
      Choco Uninstall emacs-full -y
      Choco Install emacs-full -source .\ -y
  displayName: 'Build Chocolatey package'
